package com.example.jkbsg.utils;

public class HtmlData {
    public static final String KEY_INTRODUCTION_STRING = "<h2 style=\"line-height: 1.5; text-align: justify;\"><span style='font-size: 20px; font-family: \"Times New Roman\", Times, serif;'><br></span></h2>\n" +
            "<h2 style=\"line-height: 1.5; text-align: center;\"><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 30px; color: rgb(85, 57, 130);\">INTRODUCTION</span></span></h2>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\">&nbsp; &nbsp; &nbsp;Scouting is an internationally recognized and potentially effective medium of value based educational movement for young people to develop their full emotional, intellectual, physical, social and spiritual potentials as individuals, as citizens, and as members of their local, national, and international communities.</span></span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\">The mission of scouting is to contribute to the education of young people, through a specific value system based on the Scout Promise and Law. It helps build a better world where people are self-fulfilled as individuals and play a constructive role in the society. It promotes sustainable development - by constantly addressing issue of our social utility and by providing original approaches to several of the problems affecting young people today: education, employment, gender equality, participation, and spirituality.</span></span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\">Scouting crosses borders through inter - cultural, inter - generational, and inter - religious dialogue. And in doing so, we promote a culture of equality and tolerance. It is about learning to live together and adhering to the values of peace, team work and understanding other people. It promotes critical thinking and reflective learning. Scouting cultivates lifelong values, skills and capabilities. The skills and values acquired as a Scout accompany the individual throughout his or her family, personal and work life. It promotes civic engagement on mass level but as a volunteer movement. Scouts are devoted to serving their communities and getting them engaged in finding solutions to their problems, and create lifelong active citizens. Scout Movement is a social force that promotes a culture of peace and is engaged in peace education ensuing a Scouts capacity for peace on personal, local and global level.</span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.5; text-align: justify; font-family: \"\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\"\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\">Since its founding in 1907, millions of people around the world have been able to gain from the opportunities that Scouting has been able to offer, benefiting them and society in numerous ways.. In a world full of negatives, scouting is POSITIVE. Through scouting we are on a mission to &quot;CREATE A BETTER WORLD&quot;.</span></span></p>\n" +
            "<p style='text-align: justify; font-family: \"\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\">The Boy Scouts Movement had a simple start in the year 1907 when a retired Army General Lord Baden Powell conducted an experimental camp in Brown sea Island in England with 20 boys. The successful conduct of the camp and publication of the Book &ldquo;Scouting for Boys&rdquo; in a fortnightly marked the start of the Boy Scout Movement.&nbsp;</span></span></p>\n" +
            "<p style='text-align: justify; font-family: \"\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><span lang='\\\\\\\\\\\\\\\"en-IN\\\\\\\\\\\\\\\"'>In the year 1910, Crystal palace Rally was held where Girls wearing the boy Scout uniform appeared and wanted to join the Scout Movement. Lord Baden Powell decided to start a movement for Girls with the help of his sister Agnes Baden Powell.</span></span></span></p>\n" +
            "<p style='text-align: justify; font-family: \"\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><br></span></span></p>\n" +
            "<h2 style='text-align: center; font-family: \"\\\"\\\\\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 30px;\"><strong><span style=\"color: rgb(85, 57, 130);\">Scouting in India</span></strong></span></span></h2>\n" +
            "<p style='text-align: justify; font-family: \"\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\">Scouting started in India in the year 1909, when Captain T.H.Baker established the first Scout Troop in Bangalore and got it registered with imperial Headquarters, London. subsequently, Scout Troops were formed in Kirkee (Pune), Shimla, Madras, Jabalpur, Lonavla (Mumbai) and registered with the Imperial Headquarters during 1910 and 1911. These units were open to European and Anglo Indian Children only.&nbsp;</span></span></p>\n" +
            "<p style='text-align: justify; font-family: \"\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\">The first Guide Company in India was started in Jabalpur, Central India &nbsp;in 1911.</span></span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><br></span></span></p>\n" +
            "<h2 style='text-align: center; font-family: \"\\\"\\\\\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 30px;\"><strong><span style=\"color: rgb(85, 57, 130);\">Scouting in J&amp;K</span></strong></span></span></h2>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><br></span></span></p>\n" +
            "<p style='text-align: justify; font-family: \"\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\">Data Not Available.....!</span></span></p>\n" +
            "<p style='text-align: justify; font-family: \"\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><br></span></span></p>\n" +
            "<h2 style='text-align: center; font-family: \"\\\"\\\\\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 30px;\"><strong><span style=\"color: rgb(85, 57, 130);\">Scouting in Budgam</span></strong></span></span></h2>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><br></span></span></p>\n" +
            "<p style='text-align: justify; font-family: \"\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style='font-size: 20px; font-family: \"Times New Roman\", Times, serif;'>Data Not Available.....!</span></p>";

    public static final String KEY_WHAT_ARE_WE = "<p style=\"line-height: 1.5; text-align: center;\"><span style=\"font-size: 30px;\"><span style=\"color: rgb(85, 57, 130);\"><strong>What We Do</strong></span><strong>&nbsp;</strong></span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-size: 20px;\">Scouting provides young people with opportunities to participate in programmes, events, activities and projects that contribute to their growth as active citizens. Through these initiatives, young people become agents of positive change who inspire others to take action.&nbsp;</span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: center;\"><span style=\"font-size: 30px;\"><strong><span style=\"color: rgb(85, 57, 130);\">Our Key Initiatives</span></strong> </span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-size: 20px;\">Scouts are creating a better world for their communities through our World Scout Programmes, Join them!&nbsp;</span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: center;\"><span style=\"font-size: 30px;\"><strong><span style=\"color: rgb(85, 57, 130);\">Mission</span></strong> </span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-size: 20px;\">&quot;The Mission of Scouting is to contribute to the education of young people, through a value system based on the Scout Promise and Law, to help build a better world where people are self-fulfilled as individuals and play a constructive role in society.&quot; The Mission was adopted at the 35th World Scout Conference in Durban, South Africa in 1999. Illustrating both the local and global impact of Scouting, the Mission of Scouting has been captured in World Scouting&rsquo;s brand as &quot;Creating a Better World&rdquo;.&nbsp;</span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: center;\"><span style=\"font-size: 30px;\"><strong><span style=\"color: rgb(85, 57, 130);\">Vision</span></strong>&nbsp;</span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-size: 20px;\">&quot;By 2023 Scouting will be the world&rsquo;s leading educational youth movement, enabling 100 million young people to be active citizens creating positive change in their communities and in the world based on shared values.&quot; The Vision for Scouting, Vision 2023, was adopted at the 40th World Scout Conference in Ljubljana, Slovenia in 2014.</span></p>";

    public static final String KEY_FUNDAMENTALS = "<p style='text-align: center; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 30px;\"><strong><span style=\"color: rgb(85, 57, 130);\">Our Fundamentals</span></strong></span></p>\n" +
            "<p style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\"><strong><em>Definitions:</em></strong> - The Bharat Scouts &amp; Guides is a voluntary, non-political, educational movement for young peoples, open to all without distinction of orgin, race or creed, in accordance with the purpose, principles and method conceived by the Founder Lord Baden Powell in 1907.&nbsp;</span></p>\n" +
            "<p style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\"><strong><em>Purpose: -&nbsp;</em></strong>The purpose of the Movement is to contribute to the development of young people in achieving their full physical, intellectual, social and spiritual potential as individuals , as responsible citizen and as members of the local, National &nbsp;and International Communities.&nbsp;</span></p>\n" +
            "<p style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\"><strong><em>Principles: -&nbsp;</em></strong>The Scout/Guide Movement is based on the following Principles:</span></p>\n" +
            "<p style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\"><strong><em>Duty to God: - </em></strong>Adherence to spiritual principles, loyalty to the religion that expresses them and acceptance of the duties resulting therefrom. \\</span></p>\n" +
            "<p style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\"><strong><em>Duty to others: - </em></strong></span></p>\n" +
            "<ul>\n" +
            "    <li style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">Loyalty to one&rsquo;s country in harmony of local and International peace, understanding and co-operation.&nbsp;</span></li>\n" +
            "    <li style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">Participation in the development of society, with recognition and respect for the dignity of one&rsquo;s fellowmen and for the integrity of the natural world.&nbsp;</span></li>\n" +
            "</ul>\n" +
            "<p style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\"><strong><em>Duty to self: - </em></strong>Responsibility for the development of oneself.&nbsp;</span></p>\n" +
            "<p style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\"><strong><em>The method: - </em></strong>The Scout/Guide method is a system of progressive self-education through.&nbsp;</span></p>\n" +
            "<ul>\n" +
            "    <li style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">A promise and law&nbsp;</span></li>\n" +
            "    <li style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">&nbsp;Learning by doing.&nbsp;</span></li>\n" +
            "    <li style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">Membership of small group under adult leadership involving progressive discovery and acceptance of responsibility and training toward self-government directed towards the development of character, and the acquisition of competence, self-reliance dependability and capacities to cooperate and to lead. Progressive and stimulating programmes of various activities based on the interest of the participants including games, useful skills and services to the community taking place largely in an outdoor setting in contact with nature.</span></li>\n" +
            "</ul>";

    public static final String KEY_PRAYER_SONG = "<p style='margin-bottom: 0cm; line-height: 100%; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><strong><span style='color: rgb(85, 57, 130); font-family: \"Times New Roman\", Times, serif; font-size: 30px;'>SCOUT/GUIDE PRAYER</span></strong></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 100%; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><br></p><audio controls=\"\" style=\"width:100%;\">\n" +
            "    <source src=\"https://learnermanipal-my.sharepoint.com/personal/suhail_abdullah_learner_manipal_edu/Documents/BudgamScouts/Scout%20Guide%20Prayer.mp3?App=OneDriveWebVideo\" type=\"audio/mpeg\"></audio>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><span style=\"color: rgb(0, 0, 0);\"><em>Daya kar dan bhakti ka,&nbsp;</em></span></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Hamein paramatma dena&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Daya karna hamari&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Atma mein shuddhata dena.&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Hamare dhyan mein aao&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Prabhu ankhon mein bas jao&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Andhere dil mein aakar ke&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Param jyoti jaga dena&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Baha do prem ki ganga&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Dilo me prem ka sagar</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>&nbsp;Hamen aapas me miljulkar&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Prabhu rehana sikha dena&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Hamara karam ho seva&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Hamara dharam ho seva&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Sada imaan ho seva&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Wo sevak char bana dena&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Vatan ke vaste jeena,&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Vatan ke vaste marna&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Vatan par jaan fida karna&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Prabhu hum ko sikha dena&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Daya kar dan bhakti ka,&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Hamein paramatma dena</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>&nbsp;Daya karna hamari&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><span style=\"color: rgb(0, 0, 0);\"><em>Atma mein shuddhata dena.</em></span></span></span></p>\n" +
            "<p style=\"text-align: center;\"><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><br></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 30px; color: rgb(85, 57, 130);\"><strong>FLAG SONG</strong></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><br></p><audio controls=\"\" style=\"width:100%;\">\n" +
            "    <source src=\"https://learnermanipal-my.sharepoint.com/personal/suhail_abdullah_learner_manipal_edu/Documents/BudgamScouts/Flag%20Song%20of%20The%20Bharat%20Scouts%20&%20Guides.mp3?App=OneDriveWebVideo\" type=\"audio/mpeg\"></audio>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Bharat Scout Guide Jhanda&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Ooncha Sada Rahega&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Ooncha Sada Rahega Jhanda&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Ooncha Sada Rahega&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Neela Rang Gagan Sa Vistrit</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>&nbsp;Brathru Bhave Failata&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Tridal Kamal Nith Teen&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Pratigna Von Ki Yad dilate.&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Aur Chakra Kahta Hai&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Pratipal Aagey Kadam Badega&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Ooncha Sada Rahega Jhanda&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Ooncha Sada Rahega&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><em>Bharat Scout Guide Jhanda&nbsp;</em></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.15; text-align: center; font-family: \\\"Times New Roman\\\", serif; font-size: 16px;'><em><span style='font-size: 20px; font-family: \"Times New Roman\", Times, serif;'>Ooncha Sada Rahega</span></em></p>";

    public static final String KEY_LAW_PROMISE = "<p style=\"text-align: center;\">\n" +
            "    <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\"><span style=\"font-size: 30px;\"><strong><span style=\"color: rgb(85, 57, 130); font-family: Helvetica;\">The Scout Promise and Law</span></strong></span></p>\n" +
            "<div class=\"field field-name-field-page-content field-type-text-long field-label-hidden\" style=\"box-sizing: border-box; margin-bottom: 20px; color: rgb(44, 44, 44); font-family: Roboto, sans-serif; font-size: 21px; line-height: 1.5; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;\">\n" +
            "    <p style=\"box-sizing: border-box; margin: 0px 0px 10px; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">The Scout Movement is based on the following principles:</span></span></p>\n" +
            "    <p style=\"box-sizing: border-box; margin: 0px 0px 10px; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\"><b style=\"box-sizing: border-box; font-weight: 700;\">Duty to God</b> - a person&rsquo;s relationship with the spiritual values of life, the fundamental belief in a force above mankind.</span></span></p>\n" +
            "    <p style=\"box-sizing: border-box; margin: 0px 0px 10px; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\"><b style=\"box-sizing: border-box; font-weight: 700;\">Duty to others</b> &ndash; a person&rsquo;s relationship with, and responsibility within, society in the broadest sense of the term: his or her family, local community, country and the world at large, as well as respect for others and for the natural world.</span></span></p>\n" +
            "    <p style=\"box-sizing: border-box; margin: 0px 0px 10px; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\"><b style=\"box-sizing: border-box; font-weight: 700;\">Duty to self</b> &ndash; a person&rsquo;s responsibility to develop his or her own potential, to the best of that person&rsquo;s ability.</span></span></p>\n" +
            "    <p style=\"box-sizing: border-box; margin: 0px 0px 10px; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">All members of the Scout Movement are required to adhere to the Scout Promise and Scout Law. The wording may vary in different National Scout Organizations as appropriate to the local culture, but they are all based on the Promise and Law originally conceived by the Founder of the Scout Movement, <a href=\"https://www.scout.org/bp\" style=\"box-sizing: border-box; background-color: transparent; color: rgb(98, 37, 153); text-decoration: none;\">Baden-Powell</a>.</span></span></p>\n" +
            "</div>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.5; text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px;'><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\"><br></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.5; text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px;'><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\"><strong>The Promise:&nbsp;</strong></span></span></p>\n" +
            "<ul>\n" +
            "    <li>\n" +
            "        <p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px; color: rgb(85, 57, 130);\"><em>Promise for the Cub is: -</em></span></span></p>\n" +
            "    </li>\n" +
            "</ul>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">&ldquo;I promise to do my best to</span></span></p>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">do my duty to God *and my country.</span></span></p>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">To keep the Cub Law and</span></span></p>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">To do a good turn every day&rdquo;</span></span></p>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style='font-family: \"Times New Roman\", Times, serif;'><span style=\"font-size: 20px;\"><em>*The word &ldquo;Dharma&rdquo; may be substituted for the word &ldquo;God&rdquo; if so desired.</em></span></span></p>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\"><br></span></span></p>\n" +
            "<ul>\n" +
            "    <li>\n" +
            "        <p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px; color: rgb(85, 57, 130);\"><em>Promise for the Bulbul is: -</em></span></span></p>\n" +
            "    </li>\n" +
            "</ul>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">Same as above with a change of &ldquo;Bulbul Law&rdquo;</span></span></p>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\"><br></span></span></p>\n" +
            "<ul>\n" +
            "    <li>\n" +
            "        <p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px; color: rgb(85, 57, 130);\"><em>Promise for the Scouts and Rover is: -</em></span></span></p>\n" +
            "    </li>\n" +
            "</ul>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">&ldquo;On my honour, I promise that I will do my best,</span></span></p>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">To do my duty to God and my country.</span></span></p>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">To help other people and to obey the Scout Law</span></span></p>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style='font-family: \"Times New Roman\", Times, serif;'><span style=\"font-size: 20px;\"><em>*The word &ldquo;Dharma&rdquo; may be substituted for the word &ldquo;God&rdquo; if so desired.</em></span></span></p>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\"><br></span></span></p>\n" +
            "<ul>\n" +
            "    <li>\n" +
            "        <p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px; color: rgb(85, 57, 130);\"><em>Promise for the Guide and Ranger is: -</em></span></span></p>\n" +
            "    </li>\n" +
            "</ul>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">&ldquo;On my honour, I promise that I will do my best,</span></span></p>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">To do my duty to God and my country.</span></span></p>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">To help other people and to obey the Guide Law</span></span></p>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style='font-family: \"Times New Roman\", Times, serif;'><span style=\"font-size: 20px;\"><em>*The word &ldquo;Dharma&rdquo; may be substituted for the word &ldquo;God&rdquo; if so desired.</em></span></span></p>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\"><br></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.5; text-align: center; font-family: \"Times New Roman\", serif; font-size: 16px;'><span style=\"font-family: Helvetica;\"><span style=\"font-size: 30px; color: rgb(85, 57, 130);\"><strong>The Law</strong></span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.5; text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px;'><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\"><em>The law for the Scout and the Rover is</em></span></span></p>\n" +
            "<ol type=\"i\">\n" +
            "    <li>\n" +
            "        <p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">A Scout/Rover is Trustworthy.</span></span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">A Scout/Rover is loyal.</span></span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">A Scout /Rover is a friend to all and a brother to every other Scout.</span></span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">A Scout/ Rover is courteous.</span></span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">A Scout/ Rover is friend to animals and loves nature.</span></span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">A Scout/ Rover is disciplined and helps protect public property.</span></span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">A Scout/ Rover is courageous.</span></span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">A Scout/ Rover is thrifty.</span></span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">A Scout/ Rover is pure in thought, word and deed.</span></span></p>\n" +
            "    </li>\n" +
            "</ol>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.91cm;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\"><br></span></span></p>\n" +
            "<ol>\n" +
            "    <li>\n" +
            "        <p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify;\"><span style='font-family: \"Times New Roman\", Times, serif;'><span style=\"font-size: 20px;\"><em>The law for the Guide and the Ranger is the same as above replacing the word &ldquo;Guide/Ranger&rdquo; in place of word &ldquo;Scout/Rover&rdquo;.</em></span></span></p>\n" +
            "    </li>\n" +
            "</ol>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\"><br></span></span></p>\n" +
            "<ol start=\"2\">\n" +
            "    <li>\n" +
            "        <p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px; color: rgb(85, 57, 130);\"><strong>The Law for the Cub is:</strong> </span></span></p>\n" +
            "    </li>\n" +
            "</ol>\n" +
            "<ol type=\"i\">\n" +
            "    <li>\n" +
            "        <p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">The Cub is obedient :</span></span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\">The Cub is clean and polite:</span></span></p>\n" +
            "    </li>\n" +
            "</ol>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 2.54cm;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px;\"><br></span></span></p>\n" +
            "<ol start=\"3\">\n" +
            "    <li>\n" +
            "        <p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify;\"><span style=\"font-family: Helvetica;\"><span style=\"font-size: 20px; color: rgb(85, 57, 130);\"><strong>The Law for the Bulbul is:</strong> </span></span></p>\n" +
            "    </li>\n" +
            "</ol>\n" +
            "<p style=\"margin-bottom: 0cm; line-height: 1.5; text-align: justify; margin-left: 1.27cm;\"><span style='font-size: 20px; font-family: \"Times New Roman\", Times, serif;'><em>Same as above replacing &ldquo;Bulbul&rdquo; in place of &ldquo;Cub&rdquo;</em></span></p>";

    public static final String KEY_DISTRICT_AIMS = "<p style='color: rgb(0, 0, 0); text-align: center; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><strong><span style=\"font-size: 20px; color: rgb(184, 49, 47);\">AIMS AND OBJECTIVES OF DISTRICT ASSOCIATION</span></strong></p>\n" +
            "<p style='color: rgb(0, 0, 0); text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px; color: rgb(85, 57, 130);\">It is said that the best way to teach youth to be good is to guide and prepare them in doing good. Practice and preaching should go together or better still practice should precede precept. This is the aim &amp; objective of this creative Movement called Scouting &amp; Guiding. It, therefore, aims at to provide young boys and girls (Bunnies, Cubs/Bulbuls, Scouts/Guides, Rovers/Rangers and Scouters/Guiders) opportunities to ;</span></p>\n" +
            "<ul>\n" +
            "    <li>\n" +
            "        <p style='color: rgb(0, 0, 0); text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">have a useful and enjoyable time in the open air, outside school hours ;</span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style='color: rgb(0, 0, 0); text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">have training and guidance in the habits of self-control, self-help, self-reliance and self-sacrifice ;</span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style='color: rgb(0, 0, 0); text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">find an environment for character building, so that they become better men/women and citizens, not only of their mother land but of the whole-world ;</span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style='color: rgb(0, 0, 0); text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">develop in them the spirit of seva-service through altruistic living i.e. living for others and also the civic sense in order to live purer, nobler and healthier lives ;</span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style='color: rgb(0, 0, 0); text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">cultivate in them honour, commitment, dedication, conviction, courtesy, loyalty, obedience, trust worthiness, integrity and grace ;</span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style='color: rgb(0, 0, 0); text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">show reverence for the great ones, the seers and sages, the heroes and the Holy men of their own religion, of other faiths, other religions, &amp; other countries and above the humanity ;</span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style='color: rgb(0, 0, 0); text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">form sound health habits ;</span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style='color: rgb(0, 0, 0); text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">provide training in some handicrafts and skills of daily use ;</span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style='color: rgb(0, 0, 0); text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">inculcate in them a habit of doing good turn. The Scout method is eminently practical &ldquo;DO&rdquo; rather than &ldquo;Read about&rdquo; is its characteristics</span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style='color: rgb(0, 0, 0); text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">dilate on the spirit of goodwill, mutual understanding, tolerance, truth and justice in place of envy, hatred and malice ;</span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style='color: rgb(0, 0, 0); text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">have in them a sense of responsibility and trust worthiness and to develop initiative and leadership qualities in them ; and</span></p>\n" +
            "    </li>\n" +
            "    <li>\n" +
            "        <p style='color: rgb(0, 0, 0); text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">imbibe spiritual qualities by opening their spiritual nature as this movement believes that man is essentially a spirit. He is not a body. He is not body, mind complex, he is a social human being.</span></p>\n" +
            "    </li>\n" +
            "</ul>";
}
