package com.example.jkbsg.utils;

public class HtmlData {
    public static final String KEY_INTRODUCTION_STRING = "<h2 style=\"line-height: 1.5; text-align: justify;\"><span style='font-size: 20px; font-family: \"Times New Roman\", Times, serif;'><br></span></h2>\n" +
            "<h2 style=\"line-height: 1.5; text-align: center;\"><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 30px; color: rgb(85, 57, 130);\">INTRODUCTION</span></span></h2>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\">&nbsp; &nbsp; &nbsp;Scouting is an internationally recognized and potentially effective medium of value based educational movement for young people to develop their full emotional, intellectual, physical, social and spiritual potentials as individuals, as citizens, and as members of their local, national, and international communities.</span></span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\">The mission of scouting is to contribute to the education of young people, through a specific value system based on the Scout Promise and Law. It helps build a better world where people are self-fulfilled as individuals and play a constructive role in the society. It promotes sustainable development - by constantly addressing issue of our social utility and by providing original approaches to several of the problems affecting young people today: education, employment, gender equality, participation, and spirituality.</span></span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\">Scouting crosses borders through inter - cultural, inter - generational, and inter - religious dialogue. And in doing so, we promote a culture of equality and tolerance. It is about learning to live together and adhering to the values of peace, team work and understanding other people. It promotes critical thinking and reflective learning. Scouting cultivates lifelong values, skills and capabilities. The skills and values acquired as a Scout accompany the individual throughout his or her family, personal and work life. It promotes civic engagement on mass level but as a volunteer movement. Scouts are devoted to serving their communities and getting them engaged in finding solutions to their problems, and create lifelong active citizens. Scout Movement is a social force that promotes a culture of peace and is engaged in peace education ensuing a Scouts capacity for peace on personal, local and global level.</span></span></p>\n" +
            "<p style='margin-bottom: 0cm; line-height: 1.5; text-align: justify; font-family: \"\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\"\", serif; font-size: 16px;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\">Since its founding in 1907, millions of people around the world have been able to gain from the opportunities that Scouting has been able to offer, benefiting them and society in numerous ways.. In a world full of negatives, scouting is POSITIVE. Through scouting we are on a mission to &quot;CREATE A BETTER WORLD&quot;.</span></span></p>\n" +
            "<p style='text-align: justify; font-family: \"\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\">The Boy Scouts Movement had a simple start in the year 1907 when a retired Army General Lord Baden Powell conducted an experimental camp in Brown sea Island in England with 20 boys. The successful conduct of the camp and publication of the Book &ldquo;Scouting for Boys&rdquo; in a fortnightly marked the start of the Boy Scout Movement.&nbsp;</span></span></p>\n" +
            "<p style='text-align: justify; font-family: \"\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><span lang='\\\\\\\\\\\\\\\"en-IN\\\\\\\\\\\\\\\"'>In the year 1910, Crystal palace Rally was held where Girls wearing the boy Scout uniform appeared and wanted to join the Scout Movement. Lord Baden Powell decided to start a movement for Girls with the help of his sister Agnes Baden Powell.</span></span></span></p>\n" +
            "<p style='text-align: justify; font-family: \"\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><br></span></span></p>\n" +
            "<h2 style='text-align: center; font-family: \"\\\"\\\\\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 30px;\"><strong><span style=\"color: rgb(85, 57, 130);\">Scouting in India</span></strong></span></span></h2>\n" +
            "<p style='text-align: justify; font-family: \"\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\">Scouting started in India in the year 1909, when Captain T.H.Baker established the first Scout Troop in Bangalore and got it registered with imperial Headquarters, London. subsequently, Scout Troops were formed in Kirkee (Pune), Shimla, Madras, Jabalpur, Lonavla (Mumbai) and registered with the Imperial Headquarters during 1910 and 1911. These units were open to European and Anglo Indian Children only.&nbsp;</span></span></p>\n" +
            "<p style='text-align: justify; font-family: \"\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\">The first Guide Company in India was started in Jabalpur, Central India &nbsp;in 1911.</span></span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><br></span></span></p>\n" +
            "<h2 style='text-align: center; font-family: \"\\\"\\\\\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 30px;\"><strong><span style=\"color: rgb(85, 57, 130);\">Scouting in J&amp;K</span></strong></span></span></h2>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><br></span></span></p>\n" +
            "<p style='text-align: justify; font-family: \"\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\">Data Not Available.....!</span></span></p>\n" +
            "<p style='text-align: justify; font-family: \"\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><br></span></span></p>\n" +
            "<h2 style='text-align: center; font-family: \"\\\"\\\\\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 30px;\"><strong><span style=\"color: rgb(85, 57, 130);\">Scouting in Budgam</span></strong></span></span></h2>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-family: 'Times New Roman', Times, serif;\"><span style=\"font-size: 20px;\"><br></span></span></p>\n" +
            "<p style='text-align: justify; font-family: \"\\\"\\\\\\\\\\\\\\\"Times New Roman\\\\\\\\\\\\\\\"\\\"\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style='font-size: 20px; font-family: \"Times New Roman\", Times, serif;'>Data Not Available.....!</span></p>";

    public static final String KEY_WHAT_ARE_WE = "<p style=\"line-height: 1.5; text-align: center;\"><span style=\"font-size: 30px;\"><span style=\"color: rgb(85, 57, 130);\"><strong>What We Do</strong></span><strong>&nbsp;</strong></span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-size: 20px;\">Scouting provides young people with opportunities to participate in programmes, events, activities and projects that contribute to their growth as active citizens. Through these initiatives, young people become agents of positive change who inspire others to take action.&nbsp;</span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: center;\"><span style=\"font-size: 30px;\"><strong><span style=\"color: rgb(85, 57, 130);\">Our Key Initiatives</span></strong> </span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-size: 20px;\">Scouts are creating a better world for their communities through our World Scout Programmes, Join them!&nbsp;</span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: center;\"><span style=\"font-size: 30px;\"><strong><span style=\"color: rgb(85, 57, 130);\">Mission</span></strong> </span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-size: 20px;\">&quot;The Mission of Scouting is to contribute to the education of young people, through a value system based on the Scout Promise and Law, to help build a better world where people are self-fulfilled as individuals and play a constructive role in society.&quot; The Mission was adopted at the 35th World Scout Conference in Durban, South Africa in 1999. Illustrating both the local and global impact of Scouting, the Mission of Scouting has been captured in World Scouting&rsquo;s brand as &quot;Creating a Better World&rdquo;.&nbsp;</span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: center;\"><span style=\"font-size: 30px;\"><strong><span style=\"color: rgb(85, 57, 130);\">Vision</span></strong>&nbsp;</span></p>\n" +
            "<p style=\"line-height: 1.5; text-align: justify;\"><span style=\"font-size: 20px;\">&quot;By 2023 Scouting will be the world&rsquo;s leading educational youth movement, enabling 100 million young people to be active citizens creating positive change in their communities and in the world based on shared values.&quot; The Vision for Scouting, Vision 2023, was adopted at the 40th World Scout Conference in Ljubljana, Slovenia in 2014.</span></p>";

    public static final String KEY_FUNDAMENTALS = "<p style='text-align: center; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 30px;\"><strong><span style=\"color: rgb(85, 57, 130);\">Our Fundamentals</span></strong></span></p>\n" +
            "<p style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\"><strong><em>Definitions:</em></strong> - The Bharat Scouts &amp; Guides is a voluntary, non-political, educational movement for young peoples, open to all without distinction of orgin, race or creed, in accordance with the purpose, principles and method conceived by the Founder Lord Baden Powell in 1907.&nbsp;</span></p>\n" +
            "<p style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\"><strong><em>Purpose: -&nbsp;</em></strong>The purpose of the Movement is to contribute to the development of young people in achieving their full physical, intellectual, social and spiritual potential as individuals , as responsible citizen and as members of the local, National &nbsp;and International Communities.&nbsp;</span></p>\n" +
            "<p style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\"><strong><em>Principles: -&nbsp;</em></strong>The Scout/Guide Movement is based on the following Principles:</span></p>\n" +
            "<p style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\"><strong><em>Duty to God: - </em></strong>Adherence to spiritual principles, loyalty to the religion that expresses them and acceptance of the duties resulting therefrom. \\</span></p>\n" +
            "<p style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\"><strong><em>Duty to others: - </em></strong></span></p>\n" +
            "<ul>\n" +
            "    <li style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">Loyalty to one&rsquo;s country in harmony of local and International peace, understanding and co-operation.&nbsp;</span></li>\n" +
            "    <li style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">Participation in the development of society, with recognition and respect for the dignity of one&rsquo;s fellowmen and for the integrity of the natural world.&nbsp;</span></li>\n" +
            "</ul>\n" +
            "<p style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\"><strong><em>Duty to self: - </em></strong>Responsibility for the development of oneself.&nbsp;</span></p>\n" +
            "<p style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\"><strong><em>The method: - </em></strong>The Scout/Guide method is a system of progressive self-education through.&nbsp;</span></p>\n" +
            "<ul>\n" +
            "    <li style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">A promise and law&nbsp;</span></li>\n" +
            "    <li style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">&nbsp;Learning by doing.&nbsp;</span></li>\n" +
            "    <li style='text-align: justify; font-family: \"Times New Roman\", serif; font-size: 16px; margin-bottom: 0cm; line-height: 1.5;'><span style=\"font-size: 20px;\">Membership of small group under adult leadership involving progressive discovery and acceptance of responsibility and training toward self-government directed towards the development of character, and the acquisition of competence, self-reliance dependability and capacities to cooperate and to lead. Progressive and stimulating programmes of various activities based on the interest of the participants including games, useful skills and services to the community taking place largely in an outdoor setting in contact with nature.</span></li>\n" +
            "</ul>";

    public static final String KEY_HEADLINE = "<p dir=\"ltr\"><span style=\"color:purple\"><strong><span style=\"font-size:26px\">";
    public static final String KEY_HEADLINE_AUTHOR = "</span></strong></span></p><p dir=\"ltr\"><span style=\"font-size:12px\"><span style=\"color:GREY\"><strong>BY </strong></span><span style=\"color:black\"><strong>";
    public static final String KEY_HEADLINE_TIME_STAMP = "</strong></span><span style=\"color:GREY\"><strong> ON ";
    public static final String KEY_HEADLINE_TERMINATOR = "</strong></span></span></p><hr />";
}
